name: vost
description: Aplicação para VOST

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  #built_value
  built_collection: ^4.1.0
  built_value: ^6.3.0

  #core
  rxdart: ^0.20.0
  shared_preferences: ^0.4.3
  stream_disposable: ^0.0.1

  # Network
  dio: 2.1.0
  http: ^0.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true